### ISSUE TITLE
Submit order error

### ISSUE THREAD

**Issue by johnaugusti** [mdkrieg/node-red-contrib-alpaca#4]
Receiving a 
{“code”:40010000,“message”:“request body format is invalid”}

when trying to push through an order, other nodes have been working as expected.

**Comment by mdkrieg** [comment]
I think this means a parameter is not getting set with the correct name. I
think "time in force" and "order type" have confused me before, check those
out at the bottom of this message. Also, does it work if you program all
the parameters in the node and just use an inject to submit?

If you need a workaround, there's a createOrder function in the universal
Alpaca node that does the same thing, it may work for you.

from the code (map to a value on the right):
req.type = msg.payload.type || msg.type
req.time_in_force = msg.payload.tif || msg.tif

Let me know how it goes,
-Matt

**Comment by mdkrieg** [comment]
Just checked and turned out I had the wrong parameter in the html template.

Order type calls for ".ordertype" but in fact should be ".type".

I'll publish the change to npm sometime over the next few days, until then,
change your code to use ".type" and it should work.

Thanks for your feedback on the project!
-Matt
